version: '3'

services:
  db:
    image: postgres:14.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "5432"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - project:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  project: