# Generated by Django 4.1.4 on 2022-12-29 04:58

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('timezone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код мобильного оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки сообщения')),
                ('status', models.BooleanField(choices=[('send', 'Отправлено'), ('fail', 'Не отправлено')], default='send', verbose_name='Статус отправки сообщения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='distribution.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='distribution.mailing', verbose_name='Рассылка')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='phone_code',
            field=models.ManyToManyField(to='distribution.phonecode', verbose_name='Код мобильного оператора'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag',
            field=models.ManyToManyField(to='distribution.notificationtags', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.phonecode', verbose_name='Код мобильного оператора'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(to='distribution.notificationtags', verbose_name='Тег'),
        ),
    ]
