# Generated by Django 4.1.4 on 2022-12-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='tag',
            field=models.ManyToManyField(blank=True, to='distribution.notificationtags', verbose_name='Тег'),
        ),
    ]
